# Generated by Django 3.2.15 on 2023-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0002_auto_20230816_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
